for aftel in range(30,-1,-1):
    print("rocket launching in: " + str(aftel))
print("")
print("Ready for takeoff")
print("                 ")
print("        /\       ")
print("       /  \      ")
print("      /    \     ")
print("      |    |     ")
print("      |    |     ")
print("      |    |     ")
print("      |    |     ")
print("      |    |     ")
print("     /      \    ")
print("     --    --    ")
print("     vvvvvvvv    ")